### ISSUE TITLE
Keyboard shortcut CTRL-F4 not working

### ISSUE THREAD

**Issue by JonnyTech** [fredvs/ideU#1]
The keyboard shortcut to close an open file (CTRL+F4) is not working. Other shortcuts seem to work correctly. Selecting "Close File" from the tab menu or the main menu seem to be the only way to close the current file.

**Comment by JonnyTech** [comment]
The bug also affects MSEide so have reported it there as well: [bug report](https://sourceforge.net/p/mseide-msegui/bugs/12/)

**Comment by fredvs** [comment]
Ha ok, many thanks to report it.
OK, I will first see what Martin say before to jump into code.
Fre;D

**Comment by JonnyTech** [comment]
Martin replied and a fix was found - my window manager was catching the key combination. Strange that nothing else was affected but at least I now have a solution.

**Comment by fredvs** [comment]
OK, super, nice that you find a solution.
Fre;D
