### ISSUE TITLE
Using bigger font results in overlapping layout

### ISSUE THREAD

**Issue by circular17** [fredvs/ideU#14]
![ideU_setting](https://user-images.githubusercontent.com/9092455/79080496-ae489900-7d15-11ea-8253-d282160ba5bf.png)

![ideU_extrasetting](https://user-images.githubusercontent.com/9092455/79080509-c9b3a400-7d15-11ea-921d-4682122593e1.png)

**Comment by fredvs** [comment]
Hou, ok, will do it asap, or do you agree to keep for all the dialog form the original font?

Or you prefer that all the dialog forms also have the new selected font?

**Comment by circular17** [comment]
There is no rush.

I think that it would make more sense to use the selected font everywhere.

**Comment by fredvs** [comment]
> There is no rush.

Too late, I am already inside...

**Comment by fredvs** [comment]
Hello.
Should be fixed with commit 45b2d31.
Fre;D

**Comment by circular17** [comment]
It works well. I was impressed it changed the layout in realtime. Congrats.

**Comment by fredvs** [comment]
Thanks. ;)
Layout and Syntax definition files can be changed in realtime.
The same for extra configuration.
