### ISSUE TITLE
Load layout window has fixed size

### ISSUE THREAD

**Issue by circular17** [fredvs/ideU#15]
The layout system is a great idea. 

I noticed the window has fixed size, and with big fonts, that's a bit too narrow.
![ideU_load_layout](https://user-images.githubusercontent.com/9092455/79080600-9b829400-7d16-11ea-814c-3262203b4dd2.png)

I suggest to set the window size by scaling it to the interface font.

**Comment by fredvs** [comment]
It is the same problem as previous issue.

So, do you agree to keep the original font for all the dialog forms or do you really prefer to apply this for all the dialog forms?

**Comment by circular17** [comment]
Bigger font everywhere :)

**Comment by fredvs** [comment]
> Bigger font everywhere :)

Aaaargh.
OK, some (lot of) cups of coffee and I jump into it.

See you later.

**Comment by circular17** [comment]
Good luck my friend

**Comment by fredvs** [comment]
Hello.
Should be fixed with commit 45b2d31.
Fre;D

**Comment by circular17** [comment]
I was able to compile easily. That's great now.
