### ISSUE TITLE
CTRL-T and CTRL-Y

### ISSUE THREAD

**Issue by circular17** [fredvs/ideU#16]
I am used to CTRL-T to remove a word and CTRL-Y to remove a line. Is there another shortcut for that in ideU or a configuration of keyboard shortcuts?

**Comment by fredvs** [comment]
I fear that those shortcuts are not enabled, I will see what I can do.

But did you see that 2 x click select the word and 3 x click select the line?

**Comment by circular17** [comment]
Ok. Just a note: CTRL-T is used by for Select Code Template.

Yep I can click and my hand cannot click too much.

**Comment by fredvs** [comment]
You may assign all the shortcut you want.
Go in menu Settings-General Settings and choose tab Other.

Click on the Shortcut button.

Note that you will need the last commit 0156be0, yesterday I disabled the button (do no why).

**Comment by fredvs** [comment]
![Capture d’écran_2020-04-14_20-56-13](https://user-images.githubusercontent.com/3421249/79263021-79158580-7e92-11ea-9d5e-7f77689ab0bd.png)

**Comment by circular17** [comment]
I could open it with latest commit. Thanks.

There does not seem to be Delete line or Delete word actions.

**Comment by fredvs** [comment]
> There does not seem to be Delete line or Delete word actions.

OK, I will check that.

**Comment by circular17** [comment]
In fact I just seen _Delete row_. And indeed a row is a line. I am ashamed.

Though it asks everytime for the confirmation. So maybe add _Delete row without confirmation_?

**Comment by fredvs** [comment]
> Though it asks everytime for the confirmation. So maybe add Delete row without confirmation?

OK, I will see what I can do.

**Comment by fredvs** [comment]
Would you be happy if, in place to add some new shortcuts, a new option is added in extra-config?

It would be: "Would you like to disable confirmation messages?"

**Comment by fredvs** [comment]
In last commit 45ff3f0 was added a option in Extra Settings to disable confirmation dialog.
Maybe it is enough for you?

**Comment by circular17** [comment]
Yep perfect!

**Comment by circular17** [comment]
What about CTRL-T to remove a word?

**Comment by fredvs** [comment]
> What about CTRL-T to remove a word?

Ha, you did not forget this one!
OK, I will see what I can do (but like explained before, for this the enum of shortcut must be changed but , ok, I will see).

**Comment by fredvs** [comment]
> What about CTRL-T to remove a word?

Not sure to understand what you want.
Do you want to delete the word where is the caret?
2x click + delete is not ok?

**Comment by circular17** [comment]
Personnally I don't use much CTRL-T on an emptyline, and just pressing Del can do the same so you can forget about this particular case.

**Comment by fredvs** [comment]
Is it ok for CTRL-T with caret on a word to delete all the word (not only what is after the caret)?

**Comment by circular17** [comment]
Hmm that would be a bit confusing I guess.

**Comment by fredvs** [comment]
OK.
But sorry this I cannot do now, I am over-booked.
But asap, sure.

**Comment by circular17** [comment]
No problemo

**Comment by fredvs** [comment]
Hello.

In last commit 152957c was added a shortcut "Edit - Delete word".
By default the shorcut Ctrl+T is assigned but you may change it in the shortcut list.

I hope it is ok.

**Comment by circular17** [comment]
Ok that's good. I will see how it goes using it.

Why not keep for example CTRL-ALT-T for insert template?

**Comment by fredvs** [comment]
You have to first assign something else for template like you show, and then assign "Delete word at cursor".

This because it is not the first time you load ideU and the default CTRL+T was assigned in previous for Template.

Why not keep for example CTRL-ALT-T for insert template?
Yes, all what you want, just dont use a existing one.

**Comment by fredvs** [comment]
![Capture d’écran_2020-04-17_18-55-08](https://user-images.githubusercontent.com/3421249/79594258-ff250c80-80dc-11ea-8e5b-524f23223c41.png)

**Comment by circular17** [comment]
Alright
