### ISSUE TITLE
set compile output path

### ISSUE THREAD

**Issue by circular17** [fredvs/ideU#18]
When I compile a sample project that uses BGRABitmap, it puts .o and .ppu files in the folder of BGRABitmap. I would like to choose the output path.

By the way the tab Make is artistic:
![ideu_makeoptions](https://user-images.githubusercontent.com/9092455/79472192-d0873300-8003-11ea-8935-4e1e23e0747f.png)

**Comment by fredvs** [comment]
Add line in Make option `-FUthediryouwant.

![Capture d’écran_2020-04-16_17-23-39](https://user-images.githubusercontent.com/3421249/79474822-2e694a00-8007-11ea-8069-69abad32fca1.png)



`

**Comment by fredvs** [comment]
Ooops, I have to fix font for that Project option window too.

OK, I will do asap.

**Comment by fredvs** [comment]
For BGRAbitmap directory, of course, when you are ready, I will add a global macro:
`${BGRABITMAPDIR}`, like I did for `${FPGUIDIR}`.

**Comment by fredvs** [comment]
If you use `-FUunits`, be sure that a directory `units` exists in the root directory of project.

**Comment by fredvs** [comment]
Totally out of the subject, you may try to compile with release fpc-ootb based on fpc 3.2.0 R1.
https://github.com/fredvs/freepascal-ootb/releases

**Comment by circular17** [comment]
> Add a line in `Make` option with `-FUthediryouwant`.
> For example If you use `-FUunits`, be sure that the directory units exists in the root directory of the main program file.
Perfect thanks!

**Comment by circular17** [comment]
I am testing fpc OOTB :)

**Comment by fredvs** [comment]
> I am testing fpc OOTB :)

Brrrrr, I cross my fingers, it must be out of the box.

**Comment by circular17** [comment]
Relax I will tell you how it goes

**Comment by circular17** [comment]
Ok so how do I know if it uses the new compiler?

I have set the compiler 2 to be the 3.2.0 ootb.

Then how do I compile with it?

**Comment by fredvs** [comment]
When you have set the new compilers, see previous picture, choose in the commandor panel the option number corresponding of the compiler you want to use:

![Capture d’écran_2020-04-16_19-12-01](https://user-images.githubusercontent.com/3421249/79486040-69bf4500-8016-11ea-8c66-835146ec775f.png)

**Comment by fredvs** [comment]
> Then how do I compile with it?

See second picture from https://github.com/fredvs/ideU/issues/18#issuecomment-614736830

**Comment by circular17** [comment]
Oh ok somehow I missed the second window. 

It works!

**Comment by fredvs** [comment]
> It works!

Huh, was it out of the box?

**Comment by fredvs** [comment]
OOOps, if you try the 64 bit compiler, you should first upgrade MSEgui with last commit.
There was a incompatibility with fpc 3.2.0 that was fixed yesterday.

**Comment by circular17** [comment]
Yep, I had nothing to do in the FPC folder.

I just struggled with configuring ideU.

**Comment by fredvs** [comment]
Ha ok, you dont have Windows 64 bit.
What Windows version are you using?

**Comment by circular17** [comment]
Windows 7

**Comment by fredvs** [comment]
I did deep test on Windows 10 64 bit and did not see problems, after the patch of yesterday.

**Comment by circular17** [comment]
By patch you mean automatic update of Windows 10?

**Comment by fredvs** [comment]
> By patch you mean automatic update of Windows 10?

No, the patch for `MSEide-MSEgui` to fix incompatibility with fpc >= 3.2.0 on Windows 64 bit.

**Comment by circular17** [comment]
I am confused, so the patch works?

**Comment by fredvs** [comment]
Yes the patch in last commit of msegui:
https://github.com/mse-org/mseide-msegui/commit/7e74e926bba5680b3e9f06616c5b9b3ed7c92f85

My develop machine uses Linux 64 bit and Wine the Windows emulator.
But, to be sure, before to use wine to create the release, the first time I check on a real Windows 10 machine if all is OK.

Yesterday I did try to compile some MSEgui application with the brand new fpc-ootb Windows 64 bit and found some problems at compilation.

Note that before I never try to compile a MSEgui applications with last fpc 3.2.0 RC1, this simply because fpc does not provide a 64 bit release for Windows.

**Comment by circular17** [comment]
I see. Well all I can say is that on an old Windows 7 32-bit it works fine :-)

**Comment by fredvs** [comment]
> I see. Well all I can say is that on an old Windows 7 32-bit it works fine :-)

Yep, perfect and I agree with you Windows 7 32-bit is the best Windows OS ( after the Wine emulator, of course).

;)

**Comment by circular17** [comment]
Hehe Linux is the best ;-)

**Comment by fredvs** [comment]
> By the way the tab Make is artistic:

Should be fixed in last commit b2b1f20

Fre;D

**Comment by circular17** [comment]
That's much better indeed
