### ISSUE TITLE
Commandor / Commander?

### ISSUE THREAD

**Issue by JonnyTech** [fredvs/ideU#2]
The debugger window is titled "Commandor", should this be "Commander" ("e" not "o")?

In order to reopen it once it is closed, one has to click on "View >> Debugger". This is counter-intuitive as the window itself does not identify itself as "Debugger" elsewhere.

**Comment by fredvs** [comment]
`The debugger window is titled "Commandor", should this be "Commander" ("e" not "o")?`

Hum, no it is the "latino" way (like Terminator).

> In order to reopen it once it is closed, one has to click on "View >> Debugger". This is counter-intuitive as the window itself does not identify itself as "Debugger" elsewhere.

You are absolutely right, I will fix that asap.

Fre;D

**Comment by JonnyTech** [comment]
Ah, I see: https://en.wiktionary.org/wiki/commandor :)

**Comment by fredvs** [comment]
Hello.

Ok, fixed in last commit.

Many thanks to report it.

Fre;D
