### ISSUE TITLE
FPC compatibility

### ISSUE THREAD

**Issue by circular17** [fredvs/ideU#20]
Here are a list of changes for FPC compatibility (in _msegui\lib\common\fpccompatibility_)

Insert `mclasses` after `Classes` in uses clause of:

- fpreadxwd, fpwritepcx, fpwritetga, fpwritexpm, fpwritepnm, fpreadpcx, fpreadgif, fpreadpsd

I suggest to check as well (even if it may not be necessary for BGRABitmap):

- fpread*, fpwrite*

Following is a list of unit to add. All of them need to be tweaked with `mclasses`.

Add `zipper` unit to _fpccompatibility_ folder. It is found in _paszlib_ package of FPC.

Add some units for XML support. They are found in _fcl-xml_ package of FPC:

- `xmlread`, `xmlreader`, `xmltextreader`, `xmlwrite`

Add units from package _fcl-base_:

- `base64` , `bufstream`

**Comment by fredvs** [comment]
This seems to be a MSEide-MSEgui problem.

Please open a issue here:
https://github.com/mse-org/mseide-msegui/issues

Thanks.

**Comment by circular17** [comment]
Done: https://github.com/mse-org/mseide-msegui/issues/6
