### ISSUE TITLE
ideU forget custom shortcuts

### ISSUE THREAD

**Issue by circular17** [fredvs/ideU#21]
When I set CTRL-Y to delete a line. Close ideU and reopens it, it has forgotten the shortcut.

**Comment by fredvs** [comment]
OOoooops, indeed, ok, I will jump into it (very strange).

**Comment by fredvs** [comment]
OK, fixed with commit 60f2bc2 .

Thanks to note it.

**Comment by circular17** [comment]
Sorry but it still doesn't remember.
