### ISSUE TITLE
Delete word at cursor interferes with clipboard

### ISSUE THREAD

**Issue by JonnyTech** [fredvs/ideU#23]
Just tried the new `delete word at cursor` feature but found that it cleared the contents of my clipboard and replaced it with the deleted word. Is this by design? If so can you add an option to delete the word without touching the clipboard buffer please?

**Comment by fredvs** [comment]
Ha, ok, I did miss that, ok I will check this.
Thanks to note it.

**Comment by fredvs** [comment]
Hello.
Should be fixed in last commit 502e8d6.

Thanks to note it.

**Comment by JonnyTech** [comment]
Thanks @fredvs, shall check tomorrow.

Does lines 1280- in actionsmodule.pas also need changing?:

```
procedure tactionsmo.deletewordatcursor(const sender: tcustomaction);
begin
sourcefo.activepage.copywordatcursor();
sourcefo.activepage.edit.cutselection;

end;
```

**Comment by fredvs** [comment]
> Thanks @fredvs, shall check tomorrow.
> 
> Does lines 1280- in actionsmodule.pas also need changing?:
> 
> ```
> procedure tactionsmo.deletewordatcursor(const sender: tcustomaction);
> begin
> sourcefo.activepage.copywordatcursor();
> sourcefo.activepage.edit.cutselection;
> 
> end;
> ```

Huh, it is exactly what is changed in commit 502e8d6....

**Comment by JonnyTech** [comment]
Oh, ok, because they are two procedures at different places in the same file: `deletewordatcursor` and `ondeleteword`.

**Comment by fredvs** [comment]
> Oh, ok, because they are two procedures at different places in the same file: `deletewordatcursor` and `ondeleteword`.

Yes before the commit, now it is fixed and there is only `ondeleteword`

Note that `selectwordatcursor` was added in last commit.

**Comment by fredvs** [comment]
@JonnyTech  Ho, I apologize, you are totally right, sorry, deletewordatcursor should be replaced by selectwordatcursor.

Many thank to note it, I will fix it now.

**Comment by fredvs** [comment]
Done in commit 122f70b.
@JonnyTech : Well seen!

**Comment by JonnyTech** [comment]
Thanks Fred... don't you ever sleep??

**Comment by fredvs** [comment]
No, sorry, I dont have time for that.

;-)
