### ISSUE TITLE
if I delete the binary file manually, it doesn't recompile

### ISSUE THREAD

**Issue by circular17** [fredvs/ideU#24]
I get the error: 
`GDB: The program is not being run.`

**Comment by fredvs** [comment]
On what os?

Did you enable GDB in Project Options?

![Capture d’écran_2020-04-19_17-07-02](https://user-images.githubusercontent.com/3421249/79691567-a7171300-8260-11ea-9668-3d06994abafb.png)

You may also disable the debugger clicking on the Debug icon:

![ideudebug](https://user-images.githubusercontent.com/3421249/79691575-b8f8b600-8260-11ea-88cd-67e261ad2033.png)

**Comment by circular17** [comment]
Oops I wanted to say it doesn't recompile. I click on Run but it doesn't launch.

**Comment by circular17** [comment]
To reproduce the error:

- open a project
- compile it
- delete exe file
- click on run

**Comment by fredvs** [comment]
> To reproduce the error:

  >  open a project
  >  compile it
  >  delete exe file
   > click on run

Not sure to understand, do you want that a check is done before to run to see if the binary was not just deleted after compilation?

If so, ok, but strange to delete the binary just after compilation and then try to run it.

But maybe I miss something.

**Comment by circular17** [comment]
Well if I want to clean files to make sure it recompiles, I delete manually the .exe, the .o and .ppu files.

Because sometimes it doesn't realize something it needs to recompile.

**Comment by fredvs** [comment]
> Well if I want to clean files to make sure it recompiles, I delete manually the .exe, the .o and .ppu files.

Not sure to understand, how could the debugger debug a exe file that does not exist.
The debugger is not called before compilation has ended (afaik).

I am lost.




Is it ok when a warning message "Warning: No executable found

**Comment by circular17** [comment]
If you close ideU and reopens it, and press the play button, it detects it isn't there and compiles it.

The debugger message is misleading, the thing is that it does not compile the project.

**Comment by fredvs** [comment]
I will try to understand that tonight.
Thanks to note it.

**Comment by circular17** [comment]
You're welcome. We're going to make this ideU perfect!

**Comment by fredvs** [comment]
In commit 2390677 was added some more checking before debugging.

**Comment by circular17** [comment]
Yep that's good so we know what to do.
