### ISSUE TITLE
Keep message window while compiling

### ISSUE THREAD

**Issue by circular17** [fredvs/ideU#25]
When I compile the message window is closed/hidden. Is it possible to keep it visible?

Also if it is always hidden, I don't understand that there is an option to hide the message window when compilation is complete.

**Comment by fredvs** [comment]
>  Is it possible to keep it visible?

Yes, or using the Project Option form:

![Capture d’écran_2020-04-19_17-17-26](https://user-images.githubusercontent.com/3421249/79691803-d5492280-8261-11ea-9256-19d8d853088e.png)

Or assigning this by default with Extra-Setting:

![Capture d’écran_2020-04-19_17-18-25](https://user-images.githubusercontent.com/3421249/79691820-f0b42d80-8261-11ea-9a10-d7e58627b31b.png)

**Comment by circular17** [comment]
There is a misunderstanding. It closes the messages _before_ it starts to compile not _after_.

**Comment by fredvs** [comment]
> It closes the messages before it starts to compile not after.

Ooops, I never noted this before...
Indeed this is a bug.

Thanks to note it.
I will fix it tonight.

**Comment by fredvs** [comment]
Should be fixed in commit c62cdce

**Comment by fredvs** [comment]
Toc, toc, toc, may I close the issue?

**Comment by circular17** [comment]
That's perfect now
