### ISSUE TITLE
Redundant buttons in commandor?

### ISSUE THREAD

**Issue by circular17** [fredvs/ideU#26]
I am a basic user and I am confused by the commandor. I have some suggestions and question to make it more understandable.

In project toolbar, what are the blue buttons for?
![ideu_project_toolbar](https://user-images.githubusercontent.com/9092455/79771677-6934f000-832f-11ea-9965-25b3ba08b0ad.png)

Sidenote on layout: 

- the compile mode combobox with "M" is too small. By the way what does "M" mean? Could we have some expanation on it when we click on the dropdown button?
- the button margin is too big

In the edited file toolbar, what is the point of compiling or setting compile mode? That doesn't work anyway as the file requires other files from the project or the make directories. Could we hide that when we have opened a project?
![ideu_file_toolbar](https://user-images.githubusercontent.com/9092455/79772107-f9733500-832f-11ea-9da3-a1902d838fa0.png)

In the gray toolbar, the search in current file wouldn't be more logically in the edited file toolbar? What is the voice assist button? It doesn't seem to do anything.
![ideu_gray_toolbar](https://user-images.githubusercontent.com/9092455/79772578-86b68980-8330-11ea-9656-4d8ee5c8b2d6.png)

**Comment by fredvs** [comment]
> By the way what does "M" mean? 

"Make"

> Could we have some expanation on it when we click on the dropdown button?

When you do a compilation, you need to choose a type of compilation with "Option number" comobox

In your Project Option form, you have a list of option, form 0 to 9 + M and B (for Make and Build).
M and B are added for compatibility with MSEide options, but you can fill all what you want.

After that, before to do compilation, choose in "Option number"  the kind of compil you want, according of what you have filled in Project Option form.

> the button margin is too big

Not understand, what is the margin of the button.

> In the edited file toolbar, what is the point of compiling or setting compile mode?

The commandor form has 3 panels, the main panel, the project panel and the edited panel.
With the project panel, you compile in fact the main program file.
With the edited panel you compile only the active edited source, like Geany does.
It permits to combine different type of source in your project, C source, Java source , etc.

> What is the voice assist button?

Did you install the release of ideU because it includes the sak plugin (speech assistive kit).
The same for the fpguidesigner_ext.

I propose you to install the release and then, just replace the new compiled version of ideU.exe.

**Comment by fredvs** [comment]
> What is the voice assist button? It doesn't seem to do anything.

It is the most important and one of the reason I created ideU!

**Comment by circular17** [comment]
> Instruction (blue buttons) means CPU step -> step the assembler instructions instead of
> Pascal statements.

Oh ok. Then I suggest to change the description and mention explicitely assember.

> > the button margin is too big
> 
> Not understand, what is the margin of the button.

The spacing around the image.

> > In the edited file toolbar, what is the point of compiling or setting compile mode?
> 
> The commandor form has 3 panels, the main panel, the project panel and the edited panel.
> With the project panel, you compile in fact the main program file.
> With the edited panel you compile only the active edited source, like Geany does.
> It permits to combine different type of source in your project, C source, Java source , etc.

Hmm, couldn't that be part of the project structure to say which file is what?

**Comment by circular17** [comment]
> > What is the voice assist button?
> 
> Did you install the release of ideU because it includes the sak plugin (speech assistive kit).
> The same for the fpguidesigner_ext.
> 
> I propose you to install the release and then, just replace the new compiled version of ideU.exe.

Ok I did that. I also had to go into the settings to set the plugin directory. Finally it works.

That's a surprising feature, sure why not. I don't understand well what the computer is saying.

I suggest to display a message if the plugin is not found when we click on the button. Because it may not be trivial to know what's going on.

**Comment by circular17** [comment]
> > By the way what does "M" mean?
> 
> "Make"
> 
> > Could we have some expanation on it when we click on the dropdown button?
> 
> When you do a compilation, you need to choose a type of compilation with "Option number" comobox.
> 
> In your Project Option form, you have a list of options, form 0 to 9 + M and B (for Make and Build).
> M and B are added for compatibility with MSEide options, but you can fill all what you want.

I meant that when we click on the dropdown, to show a more expanded text, like:
- instead of M display Make in the dropdown
- instead of B display Build
- instead of 1... display Make 1

By the way, Build is useful because it seems to do a rebuild. Is it the same as a clean build where you would remove all compiled files?

**Comment by fredvs** [comment]
> Hmm, couldn't that be part of the project structure to say which file is what?

No, in the project structure you say what compiler you use for the main program file.
Also, it is much fast to directly use the Commandor to compile the edited file only.

> I meant that when we click on the dropdown, to show a more expanded text, like:

Take in account that it will take much more space in the commandor, if you want, a hint will explain trhe meaning of this.

> By the way, Build is useful because it seems to do a rebuild.

Sorry but it seems to me that you did not catch the trick.
You may assign all what you want for each enum: M B 1 2 3 4 5 6 7 8 9 0.

By convention, B is used to rebuild all (-B with fpc), but if you want you may assign something else.
For example, I use 5 6 7 8 for compiling for Windows.
4 is usually used for release, but it is convention, up to you to decide what number does what.

**Comment by fredvs** [comment]
> The spacing around the image.

Yes, I know, I wait for a more elegant solution than stretching the icon.
The goal is that the icon fits all the button.

**Comment by circular17** [comment]
> By the way, what font size are you using?

Currently 18

> In last commit icons are stretched (some but not all).

Cool

**Comment by fredvs** [comment]
>>  By the way, what font size are you using?
> Currently 18

Ha, OK, so you have a very big screen...

>>   In last commit icons are stretched (some but not all).
> Cool

Thanks!

**Comment by circular17** [comment]
> > > By the way, what font size are you using?
> > 
> > Currently 18
> 
> Ha, OK, so you have a very big screen...

Not really. But the pixels are small and it is not good quality so for my eyes it is better to have bigger stuff. And in fact I like have enormous icons. :D

**Comment by fredvs** [comment]
OK, all icons are stretched now.

I hope they are big enough....

**Comment by fredvs** [comment]
@circular17 : If you dont see any problems, maybe you can close the issue.
When all the issues are fixed, I will release ideU 2.1.0.

**Comment by circular17** [comment]
Alright
