### ISSUE TITLE
Ctrl-Click then Ctrl-H

### ISSUE THREAD

**Issue by circular17** [fredvs/ideU#28]
If I hold Ctrl and click on a unit in the uses clause, it goes to the source. Then I press Ctrl-H and it goes back. Until here that works. But now if I move the mouse, without clicking, it goes again into the second unit. Also Ctrl-H doesn't work anymore to go back.

**Comment by fredvs** [comment]
Ok, I will check that.

**Comment by fredvs** [comment]
Here it works normally, CTRL+Click goes on source and CTRL+H goes back.
Even if repeat this many times.

Sorry but I dont understand this:

>But now if I move the mouse, without clicking, it goes again into the second unit.

What goes again to the second units, what is that second units and how do you go you to that unit without clicking.  Sorry I dont understand, could you explain a few more?

**Comment by fredvs** [comment]
> But now if I move the mouse, without clicking, it goes again into the second unit. Also Ctrl-H doesn't work anymore to go back.

But for navigate, you may use Ctrl-H  to go back and Shift+Ctrl-H to go forward:

![Capture d’écran_2020-04-24_03-51-21](https://user-images.githubusercontent.com/3421249/80166760-ffdb0880-85de-11ea-918e-add92e3cbbad.png)

**Comment by circular17** [comment]
A video might help. So here I Ctrl-Click on `mseclasses` which get me to that unit. Then I press Ctrl-H and it goes back to `main`. Then I slightly move the mouse and it goes again into `mseclasses`.
![ideu_ctrl_h](https://user-images.githubusercontent.com/9092455/80186434-4562fa00-860e-11ea-8e78-190545d799e2.gif)

**Comment by fredvs** [comment]
Many thanks for the video but I am still stocked.
I try here but nothing appends.

So following your video:

1) Click on mseclasses with Ctrl+Click ----> it goes to mseclasses source.
2) When I am in mseclasses, do Ctrl + H ----> it goes back to main.pas
3) Now in main.pas I move the cursor somewhere and click ----> nothing append (like it should).

So sure I miss something but what....

**Comment by circular17** [comment]
3. Move the cursor without clicking

**Comment by circular17** [comment]
To make animated gif, in Linux terminal:
**~/Vidéos$** ffmpeg -i video.mp4 -vf "split[s0][s1];[s0]palettegen[p];[s1][p]paletteuse" video.gif

**Comment by circular17** [comment]
I can try to debug it. Where in the code are done the Ctrl-H and Ctrl-Click actions?

**Comment by circular17** [comment]
Oh in fact it seems the lamp is also creating this bug.

**Comment by fredvs** [comment]
Hello, ok, I will check this tonight.

**Comment by circular17** [comment]
Ok, see you

**Comment by fredvs** [comment]
> Oh in fact it seems the lamp is also creating this bug.

Yep, with the lamp I can reproduce the bug.
Ok, good meat for tonight.

**Comment by fredvs** [comment]
Now I have doubt about the utility of the auto-list (lamp on).
I did it in the begin of ideU to do like Delphi does but maybe it is not needed, CTRL+Space or CTRL+CTRL+Space is enough.

What do you think?

**Comment by fredvs** [comment]
>To make animated gif, in Linux terminal:
>~/Vidéos$ ffmpeg -i video.mp4 -vf "split[s0][s1];[s0]palettegen[p];[s1][p]paletteuse" video.gif

Nice trick and OOTB.
Many thanks, I will use it very soon.
;-)

**Comment by circular17** [comment]
> Now I have doubt about the utility of the auto-list (lamp on).
> I did it in the begin of ideU to do like Delphi does but maybe it is not needed, CTRL+Space or CTRL+Shif+Space is enough.
> 
> What do you think?

I agree it is not needed. Maybe it can be that when you write "." then it shows automatically the list like Ctrl+Space. Or when you write "(" it shows the parameters like Ctrl+Shift+Space. But otherwise, that's really not necessary.

**Comment by fredvs** [comment]
Huh, with last commit it should be fixed.
Personally I use it, I dont have very good memory and it helps me a lot.
And I like to not be obliged to use a key and that it comes automatic.
But people way disable it with the lamp icon.

**Comment by fredvs** [comment]
By the way, did you try the auto-class completion?

You may try it with this: copy this code in your code:

```
type TMyButton = class(TButton)
    property Size: Integer;
    procedure DoSomething;
end;

``

Place the cursor-caret on `class` and do `Shift+Ctrl+A` and see what happens (and appends).

**Comment by circular17** [comment]
Oh ok so that's like Ctrl-Shift-C. I though it wasn't available because I tried with this shortcut.

**Comment by fredvs** [comment]
> Oh ok so that's like Ctrl-Shift-C. I though it wasn't available because I tried with this shortcut.

Ha, of course you may assign the shortcut you want.
Is `Ctrl-Shift-C` the default normally used?
If yes, it could be changed as default in ideU too.

**Comment by fredvs** [comment]
If you click with the right button on the edit page, you will have a list with all the shortcut available.

![ctrlE](https://user-images.githubusercontent.com/3421249/80250223-ad97f700-8673-11ea-8c48-ed2699238662.png)

**Comment by circular17** [comment]
> Is `Ctrl-Shift-C` the default normally used?
> If yes, it could be changed as default in ideU too.

As far as I know that's the default in Lazarus. I don't know for other editors.

> If you click with the right button on the edit page, you will have a list with all the shortcuts available.

Cool yeah I could browse a bit this menu.

**Comment by fredvs** [comment]
> As far as I know that's the default in Lazarus. I don't know for other editors.

Hum, here it is used to copy cells.

**Comment by circular17** [comment]
Well one can find it in the menu anyway.

The problem with CTRL-H is solved. Congrats!
