### ISSUE TITLE
Flickering windows

### ISSUE THREAD

**Issue by JonnyTech** [fredvs/ideU#3]
The open windows flicker which can be very irritating. To show the symptoms:
- open a few windows ie main ideU, symbols, commandor
- hover mouse cursor over a commandor icon
- when the tooltip appears, all of the windows flicker

Tested with Linux64 and latest ideU (binary and recompiled)

**Comment by fredvs** [comment]
Thanks to report it.
I will check it asap.

Does it append with MSEide too ?

Thanks.

Fre;D

**Comment by JonnyTech** [comment]
I downloaded from https://github.com/fredvs/ideU/archive/master.zip
Should I be doing anything else?
MSEide does not show any flickering issues whatsoever.

**Comment by fredvs** [comment]
> I downloaded from https://github.com/fredvs/ideU/archive/master.zip

This is ok, (but did you try with the very last commits (10 minutes ago)).

> MSEide does not show any flickering issues whatsoever.

OK, I will check this asap.

Fre;D

**Comment by JonnyTech** [comment]
I am getting a compilation error:

```
Free Pascal Compiler version 3.0.0+dfsg-7 [2016/08/22] for x86_64
Copyright (c) 1993-2015 by Florian Klaempfl and others
Target OS: Linux for x86-64
Compiling ideU.pas
Compiling mseapplication.pas
Compiling msethread.pas
Compiling msestream.pas
Compiling msestat.pas
Compiling msedatalist.pas
Compiling mseact.pas
Compiling mseapplication.pas
Compiling msepipestream.pas
Compiling msestat.pas
Compiling msestatfile.pas
Compiling msearrayprops.pas
Compiling mseificomp.pas
Compiling mseificompglob.pas
Compiling msedatamodules.pas
Compiling mseskindesign.pas
Compiling msedesigner.pas
Compiling msedesignintf.pas
Compiling msedesigner.pas
Compiling msepropertyeditors.pas
Compiling mseformatpngread.pas
Compiling fpreadpng.pas
Compiling pngcomn.pp
Compiling mseformatpnmread.pas
Compiling fpreadpnm.pp
Compiling mseformattgaread.pas
Compiling fpreadtga.pp
Compiling mseformatxpmread.pas
Compiling fpreadxpm.pp
Compiling mseformattiffread.pas
Compiling fpreadtiff.pas
Compiling fptiffcmn.pas
Compiling msedesigner.pas
Compiling msecomponenteditors.pas
Compiling msedesignparser.pas
Compiling mseparser.pas
Compiling cdesignparser.pas
Compiling sourceupdate.pas
Compiling msedesigner.pas
Compiling designer_bmp.pas
Compiling formdesigner.pas
Compiling componentpaletteform.pas
Compiling componentpaletteform_mfm.pas
Compiling main.pas
Compiling plugmanager.pas
Compiling main.pas
Compiling fpg_iniutils_ideu.pas
Compiling msegdbutils.pas
Compiling actionsmodule.pas
Compiling debuggerform.pas
Compiling mseimage.pas
Compiling debuggerform_mfm.pas
Compiling actionsmodule.pas
Compiling projecttreeform.pas
Compiling projecttreeform_mfm.pas
Compiling main.pas
Compiling sak_mse.pas
sak_mse.pas(66,10) Error: Identifier not found "class"
sak_mse.pas(67,3) Error: Error in type definition
sak_mse.pas(67,3) Fatal: Syntax error, ";" expected but "identifier PROTECTED" found
Fatal: Compilation aborted
Error: /usr/bin/ppcx64 returned an error exitcode
```

Ideas?

**Comment by fredvs** [comment]
OK, I will check this tonight.
Write you later.

(I use fpc 3.1.1, I will install fpc 3.0.0 and test it)

Fre;D

**Comment by fredvs** [comment]
Hello.

Huh, tested and compiled with Linux Mint 17 64 bit... without error...
Also no flickering windows...

How did you do to download last ideU release ?

The way I do is to click on the "**Clone or download**" button of githug.com/fredvs/ideU, then on "**Download ZIP**".
See here:
![ideu_download](https://cloud.githubusercontent.com/assets/3421249/17942633/7f145c30-6a38-11e6-91b3-d5e44eb7e1d2.jpg)

Did you delete all old files in /src/units/ before to compile the new release ?

Fre;D

**Comment by fredvs** [comment]
Re-hello.

How did you do to compile ?
Did you use MSEide or compiled-ideU using ideU.prj file ? (because it is the best way).

Fre;D

**Comment by fredvs** [comment]
Re-re hello.

I think I get it ;-)

> Compiling sak_mse.pas
> sak_mse.pas(66,10) Error: Identifier not found "class"
> sak_mse.pas(67,3) Error: Error in type definition
> sak_mse.pas(67,3) Fatal: Syntax error, ";" expected but "identifier PROTECTED" found

--> this if compiling alone because this was missing:

`{$mode objfpc}{$H+}`

Huh..., could you try with last commit ?

Many thanks.

Fre;D

**Comment by JonnyTech** [comment]
Perfect! It now compiles and the flickering is gone. Thanks for your help.

**Comment by fredvs** [comment]
Yep, I am happy too.
Thanks to note it ;-)
Fre;D
