### ISSUE TITLE
Autocomplete on methods of function parameters

### ISSUE THREAD

**Issue by circular17** [fredvs/ideU#31]
If I have the following code:
```
procedure tmainfo.formpaint(const Sender: twidget; const acanvas: tcanvas);
begin
  acanvas.fill
```
with the curseur after `fill` and press Ctrl-Space to show the methods of `tcanvas`, nothing happens. It seems this happens with parameters of functions. If instead I have a local variable, it will display the methods.

```
procedure tmainfo.formpaint(const Sender: twidget; const acanvas: tcanvas);
var c: tcanvas;
begin
  c := acanvas;
  c.fill  //here it will display the list
```

**Comment by fredvs** [comment]
I fear that for tuning autocompletion, it will be in the next release.

;-(

**Comment by circular17** [comment]
No problemo. The issue can wait patiently

**Comment by circular17** [comment]
So ready to publish a new release?

**Comment by fredvs** [comment]
Even, maybe for this release, we can disable insert/append code while 2xclick.

Imho, code completion should be revised and re-thinked.

**Comment by fredvs** [comment]
> So ready to publish a new release?

I wait for your green light.

**Comment by circular17** [comment]
Hmm I think we forgot this issue:
https://github.com/mse-org/mseide-msegui/issues/9

I also just found a tiny thing:
https://github.com/fredvs/ideU/issues/33

**Comment by fredvs** [comment]
> Hmm I think we forgot this issue:
> mse-org/mseide-msegui#9

Huh, was it not solved?
Of course if you need a `.prj` fully compatible with `MSEide`, you should use, as explained, for target name: `myfilename${EXEEXT}`

This will work for both `MSEide` and `ideU`.
And for people that does poly-compilation with `ideU`, they know how to tune project-options for poly-compilation.

**Comment by fredvs** [comment]
Do not forget that a .prj saved by ideU has extended info that will be ignored by MSEide.
For example MSEide has options `M B 1 2 3 4`.
IdeU has options `M B 1 2 3 4 5 6 7 8 9 0`.

When you load a `.prj` with MSEide, options `5 6 7 8 9 0` are ignored.
The same for extension, MSEide has only one extension macro (`${EXEEXT}`), ideU has 12 macros + `${EXEEXT}` for extension.

Do you have problem to compile `ideU.prj` from last commits?
It uses `ideU${EXEEXT}` as target name.

**Comment by circular17** [comment]
Not from MSEide but from ideU. With the following config:
![image](https://user-images.githubusercontent.com/9092455/80285070-abd93c80-8722-11ea-819f-8f819dd7a5d3.png)

I get the filename "demo.exe.exe"

**Comment by fredvs** [comment]
Yes, of course.
For shared-project, for example using ideU${EXEEXT} , I set the exe extension like this:

![Capture d’écran_2020-04-25_18-41-04](https://user-images.githubusercontent.com/3421249/80285378-c6acb080-8724-11ea-9e4b-958c0066312a.png)

**Comment by fredvs** [comment]
Ooops, I will do for `ideU`, thanks to note it.

**Comment by circular17** [comment]
Hmm there may be a misunderstanding.

What I am talking about is that if there is already ${EXEEXT} in the end of the target file name, it would help not to append yet another extension.

To get the output file name that would be for example in pseudo-code:
```
function GetOutputFilename: string;
var
  fixedTargetFile, extension: string;
begin
  fixedTargetFile := Config.TargetFile;
  if not UpperCase(fixedTargetFile).EndsWith('${EXEEXT}') then
    AppendStr(fixedTargetFile, '${EXEEXT}');
  if Config.MakeExtension = '(Default)' then
    extension := GlobalConfig.EXEEXT 
  else 
    extension := Config.MakeExtension;
  result := StringReplace(fixedTargetFile, '${EXEEXT}', extension, []); 
end;
```

**Comment by fredvs** [comment]
Yes, I perfectly understood what you explained.

What can be done (maybe) if in pseudo code:

```
if not UpperCase(fixedTargetFile).EndsWith('${EXEEXT}') then
    AppendStr(fixedTargetFile,exeext[NumofOption]);
```

**Comment by fredvs** [comment]
Hum, if we follow your idea, it must be done not only for` EndsWith('${EXEEXT}')` but also for any extension added in the targetfile name.

For example, if you do:

`MyTargetfilename := 'myprog.exe'`, it should also forget the` exeext[NumofOption]`

**Comment by circular17** [comment]
Yes that would give some compatibility.

Then you need to remove ${EXEEXT} in "target file" to customize the extension, so that won't be compatible with MSEide anymore once you use this feature. Right?

**Comment by circular17** [comment]
> Hum, if we follow your idea, it must be done not only for` EndsWith('${EXEEXT}')` but also for any extension added in the targetfile name.
> 
> For example, if you do:
> 
> `MyTargetfilename := 'myprog.exe'`, it should also forget the` exeext[NumofOption]`

That's a good point.

Maybe to avoid this problem, when the Default extension is chosen, just do like MSEide.

**Comment by fredvs** [comment]
> Maybe to avoid this problem, when the Default extension is chosen, just do like MSEide.

You know, the engine is already open, my hands full of grease, I will add the simple 

`if (pos('${EXEEXT}',uppercase(targetfilename)) > 0) or  (pos('.',targetfilename) > 0) then dontaddextension;`

**Comment by circular17** [comment]
Hmm well but if someone wants to add a dot in the filename?

Like MyProgram.v2.exe ?

**Comment by fredvs** [comment]
OK, could you try with last commit?

> Like MyProgram.v2.exe?

And, no problems, I do not see the problem.

**Comment by fredvs** [comment]
> would it still replace ${EXEEXT}

Of course.

**Comment by circular17** [comment]
I understand what you did. At least that allows to keep the compatibility.

> > would it still replace ${EXEEXT}
> 
> Of course.

Well no it won't replace by the custom extension selected in the Exe extension tab. But that's ok I guess because if you start to customize the extensions then probably your project won't be compatible with MSEide anyway.

**Comment by circular17** [comment]
I tested it works. Thanks

**Comment by fredvs** [comment]
> Well no it won't replace by the custom extension selected in the Exe extension tab.

OK, in last commit 409cfd3 there is that hint:

![Sans titre](https://user-images.githubusercontent.com/3421249/80290032-1bf7ba80-8743-11ea-9522-2e61a4d7179e.png)

**Comment by circular17** [comment]
Ok.

**Comment by fredvs** [comment]
Note that the macro `${EXEEXT}` is considered as a extension, like `.exe`.

**Comment by fredvs** [comment]
> MyProgram.v2.exe

You may try, it will work.

**Comment by circular17** [comment]
Yes but I was thinking in "target file" to have "MyProgram.v2" and then to select .exe in the extension list.

**Comment by fredvs** [comment]
Ha, hum, ok, maybe a new check-box should be added "Add always extension"?

**Comment by circular17** [comment]
Hmmmm...

Or my previous suggestion (simplified):
- if Default extension is selected, do as MSEide: replace ${EXEEXT} by global extension
- otherwise remove ${EXEEXT} and add selected custom extension

**Comment by fredvs** [comment]
> if Default extension is selected

You mean in Tab "Exe Extension" ?

>  do as MSEide: replace ${EXEEXT} by global extension

Hmmmm, so first look was selected in tab and then do the check...
Re-hmmmmm, let me think about it.

**Comment by fredvs** [comment]
OK, it is late, but imho, this should work too:

First delete any  ${EXEEXT} in target file name.

   ```
 int1 := system.pos('${EXEEXT}',uppercase(targetfile));
   if int1 > 0 then targetfile := system.copy(targetfile,0,int1);
```

Then do as usual, use the selected extension....

I did commit this in 5e6f44a, what do you think?

**Comment by fredvs** [comment]
No, fake news, it does not work as wanted.
I will fix it tomorrow.

**Comment by fredvs** [comment]
OK, recommitted, this is the good one : 73bae4f

**Comment by circular17** [comment]
Hmm the code is not very readable. Can you use meaningful variable names instead of `int2`, `int3`, `int4` etc. ?

Also seems that the code is duplicated in _projectoptionsform.pas_ and _make.pas_. Is it possible to put that in one function?

**Comment by fredvs** [comment]
> Also seems that the code is duplicated in projectoptionsform.pas and make.pas. Is it possible to put that in one function?

No, it is not the same function, one is to show the command line in Project option form, the other is to create the compiler command line.

**Comment by fredvs** [comment]
> Hmm the code is not very readable. Can you use meaningful variable names instead of int2, int3, int4 etc. ?

Done in commit 1171ad4

**Comment by circular17** [comment]
Great. I tested it that's very good now.

I guess you can publish it

**Comment by fredvs** [comment]
OK, many, many thanks for all your help and lucidity.

There is some few things to tune before release but imho, it is nearly ready.
I will do it next week because I want to test it deep on each OS before to post the executable.

Have a perfect Sunday.

Fre;D

**Comment by fredvs** [comment]
> If I have the following code:
> 
> ```
> procedure tmainfo.formpaint(const Sender: twidget; const acanvas: tcanvas);
> begin
>   acanvas.fill
> ```

Hum, there is something that I miss.
Would it not be a "Can't assign values to const variable" if you use that code?

Anyway, yes, it should show the list.
I fear that this issue could be fixed only by a class-guru.

;-)

**Comment by circular17** [comment]
Hmm where will we find that?

**Comment by fredvs** [comment]
Afaik in sourceupdate.pas, function composeprocedureheader....

https://github.com/fredvs/ideU/blob/master/src/sourceupdate.pas

**Comment by circular17** [comment]
No I was talking about the guru
