### ISSUE TITLE
Selecting multiple extensions in Make

### ISSUE THREAD

**Issue by circular17** [fredvs/ideU#34]
I can select multiple extensions like that:
![image](https://user-images.githubusercontent.com/9092455/80289948-590f7d00-8742-11ea-838f-036952d00cd9.png)

Though that doesn't make sense, does it?

**Comment by fredvs** [comment]
> Though that doesn't make sense, does it?

Absolutely no sense, but the last will be used (here .prog).

**Comment by fredvs** [comment]
This one is more logical:

![Capture d’écran_2020-04-25_22-25-11](https://user-images.githubusercontent.com/3421249/80290129-b6f09480-8743-11ea-9cec-3b8b4ad647e5.png)

**Comment by circular17** [comment]
If that doesn't make sense, the interface should not allow to do that, like automatically deselecting the previous extension when selecting a new one.

**Comment by fredvs** [comment]
> the interface should not allow to do that, like automatically deselecting the previous extension when selecting a new one.

OK, chef, you are right, I will check this.

**Comment by circular17** [comment]
Well if that makes sense to you.

I guess I am going to sleep. See you tomorrow!

**Comment by fredvs** [comment]
Should be fixed with commit c9e8fb0

**Comment by circular17** [comment]
That works fine!

**Comment by fredvs** [comment]
Added the same for choice of compiler and debugger in last commit.
