### ISSUE TITLE
Error Code 3 on new mse project

### ISSUE THREAD

**Issue by lainz** [fredvs/ideU#35]
Hi, I get this error, what I've done:
- Installed FPC win32
- Installed FPC win32 x64 cross compiler
- Configured the msegui folder
- Configured the LCL folder
![compileerror](https://user-images.githubusercontent.com/4131395/93105413-6e4f5e80-f685-11ea-8646-5fac92465bed.png)

**Comment by fredvs** [comment]
Hello.

Did you create a `\units` directory?

ideU does not create it automatically.

**Comment by fredvs** [comment]
If you prefer, you may disable the `-FUunits` parameter in `Project Options` - `Make Options`.

But then all the result of compilation will be in the same directory as the source.

**Comment by fredvs** [comment]
But yes, good idea, I will think to automatic create a `\units` directory when creating a new project from template.

**Comment by lainz** [comment]
Ok thanks. Didn't know about the units directory. Yes please create it automatically if you can.

**Comment by fredvs** [comment]
Hello.

OK, in last commit 922f681, when creating a new project, the `/units` sub-directory is auto-created.
