### ISSUE TITLE
UI-tabs look werid at corners

### ISSUE THREAD

**Issue by Alexey-T** [fredvs/ideU#37]
![Screenshot from 2021-08-31 16-17-56](https://user-images.githubusercontent.com/4154978/131509487-78c55948-9047-45d9-8d84-b00450029f35.png)

**Comment by Alexey-T** [comment]
And here
![Screenshot from 2021-08-31 16-19-17](https://user-images.githubusercontent.com/4154978/131509562-769542ce-8742-4fe6-aadc-7296a7e3805c.png)

**Comment by fredvs** [comment]
Hello Alexey.

You are right, it was a old try with custom shape but indeed it is not very fine.

Reversed with more conventional menu-items and tabs in last commit f6a178ebcdff17db441da3d6ee1e24c66276f248.

Thanks to note it.

Fre;D
