### ISSUE TITLE
Filling for the selection

### ISSUE THREAD

**Issue by Alexey-T** [fredvs/ideU#38]
Here it's good to paint 1-char blue cell for empty lines!
![Screenshot from 2021-08-31 16-20-43](https://user-images.githubusercontent.com/4154978/131509872-4684fdcf-3906-4ae9-83a9-cce1f800df47.png)

W/o this 1-char filled cells, text looks like several selections.

**Comment by fredvs** [comment]
Hum.

OK, I see but for this I need more time to fix it.

Write you later.

Fre;D

**Comment by Alexey-T** [comment]
Less common than in other apps, but ok.

**Comment by fredvs** [comment]
If you want to have the same color like for other apps, you may change the color of the selected rectangle in
the _**syntaxdef**_ files.

// COLORS font/paper/statement/pairmark/fontline/line/focusline/**selected**
COLORS cl_black cl_white cl_white cl_ltyellow cl_dkgray cl_ltgray cl_white **$E6D9FF**

Replace "selected" with "cl_dkblue" for example to have the same color as selected.

// COLORS font/paper/statement/pairmark/fontline/line/focusline/selected
COLORS cl_black cl_white cl_white cl_ltyellow cl_dkgray cl_ltgray cl_white cl_dkblue

![ideu_multi_select2](https://user-images.githubusercontent.com/3421249/131560204-e8b767cd-ccdb-415b-a747-7a4f867833ae.png)
