### ISSUE TITLE
Some commands must be disabled when no editor-window is opened

### ISSUE THREAD

**Issue by Alexey-T** [fredvs/ideU#39]
e.g. "Procedure List".

![Screenshot from 2021-08-31 16-22-55](https://user-images.githubusercontent.com/4154978/131510172-db2b9918-3e7e-4218-80d9-77f000120a94.png)

**Comment by fredvs** [comment]
Hello Alexey.

You are totally right, I forgot this.

Fixed for "Procedure list" and many other things in last commit: 
7a396db67552559d095c08ffebbb5184faaec8c5

Thanks to note it.

Fre;D
