### ISSUE TITLE
Menu item sends application to back

### ISSUE THREAD

**Issue by JonnyTech** [fredvs/ideU#4]
On the main menu, selecting "File >> New" then pops up a new menu. This works fine if ideU is the only application running.

But if there is another application window open on the desktop, as soon as "File >> New" is selected then the ideU window jumps behind all other open windows.

I think that the popup is sending the main window to behind other windows and the whole application loses focus.

**Comment by fredvs** [comment]
OK, I will check this asap.
Thanks to note it.

Fre;D

**Comment by JonnyTech** [comment]
I have attached a screen recording to demonstrate the problem: [ideu-bug.zip](https://github.com/fredvs/ideU/files/438165/ideu-bug.zip)

**Comment by fredvs** [comment]
Hello Jonny.

Thanks for your video.

But..., I cannot reproduce it, on Linux Mint 17 64 bit. (see attachment)

[bug_jonny.zip](https://github.com/fredvs/ideU/files/439520/bug_jonny.zip)

Do you have the same problem with MSEide ?

Fre;D

**Comment by JonnyTech** [comment]
MSEide works perfectly. Hmm. Can you send me your compiled binary file?

**Comment by fredvs** [comment]
Hello.

Here the binary file, compiled on Linux, with fpc 3.0.0 64 bit, using last MSEgui:
[ideU.zip](https://github.com/fredvs/ideU/files/440245/ideU.zip)

Fre;D

**Comment by JonnyTech** [comment]
Thanks, your executable behaves exactly the same as mine.
Hmm, I can see myself reinstalling my operating system... :(

**Comment by fredvs** [comment]
Hello.

Could you try this:

Click on main menu item: > Settings > Extra Settings

Then, check "No Z order handling". (see picture)
![no_z](https://cloud.githubusercontent.com/assets/3421249/18028687/b54276c6-6c85-11e6-8be7-dc49b5acac2b.jpg)

This "Z order handling" feature gives focus to a window when the mouse move on it.
Maybe there is a problem with this and your window manager.

By the way, in new commit, now "No Z order handling" is checked by default for new installation.

Fre;D

**Comment by JonnyTech** [comment]
> check "No Z order handling"

Good call - that fixed it!

> Maybe there is a problem with this and your window manager

I am running plain Debian 8 Jessie 64 bit XFCE, nothing special

Thanks for your efforts

**Comment by fredvs** [comment]
Yep, super happy that it is fixed.

> I am running plain Debian 8 Jessie 64 bit XFCE, nothing special

Ha, ok, I will install **XFCE** (asap) and see what is wrong.

Many thanks to report it.

Fre;D
