### ISSUE TITLE
Which should be used: ideU or mseide-msegui?

### ISSUE THREAD

**Issue by 3oheicrw** [fredvs/ideU#40]
Are they the same? What is the different between them and which should be used? Thanks.

**Comment by fredvs** [comment]
Hello.

_mseide_ is the ide and _msegui_ are the widgets used for the ide.
_ideU_ is a fork of _mseide_ and uses so _msegui_ widgets.

Now it is a question of taste.
_mseide_ has all the basic tools to build a _msegui_ application.

_ideU_ has all the tools of _mseide_ plus many other feature, like auto-completion, multi languages, multi compilers, voice assisted and much more.

But mseide and ideU are compatible one with the other, project done with one can be loaded by the other.

Fre;D
