### ISSUE TITLE
Can't compile any project on Windows

### ISSUE THREAD

**Issue by jpgpng** [fredvs/ideU#42]
Bug: IDE uses path like this: `/C:/projects/test` so the compiler can't find the source. I guest there is typo on the path. On Windows we use backward slashes isn't it? This kind of forward slashes path can only found on Cygwin/MSYS2, but it will be `C:/projects/test` and not `/C:/projects/test`

Update: MinGW-W64 seems also understand this kind of path, but it's `C:/projects/test` not `/C:/projects/test`

**Comment by fredvs** [comment]
Hello.

How do you get that problem, could you, please, explain how the problem occurs?
Tested many projects on Windows and I dont get that slashes error.

What Windows version are you using, could you give a example or a screenshot of the error?

Thanks.

**Comment by fredvs** [comment]
Re-hello.
Do you get same problems using mseide for Windows?
https://github.com/mse-org/mseide-msegui/releases

**Comment by fredvs** [comment]
Re-re hello.

OK, I just try ideU on a Windows 10 machine and indeed, there are problems.
Sorry I did test the ideU Windows version via wine on Linux and there all is OK.

Thanks to note it, I will fix it tonight, write you later.

**Comment by 3oheicrw** [comment]
> Sorry I did test the ideU Windows version via wine on Linux and there all is OK.

This is a very bad and wrong way. People seems to expect wine is an incomplete implement of Windows API so if it runs fine on Wine it should run fine on the real Windows also?

**Comment by fredvs** [comment]
Yes, I agree, my big mistake.
I dont have any Windows OS installed, so I trusted in wine who did always exe compatible with new an older Windows release.
But it not anymore the case, as we have seen.

OK, I have to find a Windows machine and always test code on it.

**Comment by fredvs** [comment]
Hello.

The last commit [ea3c10f](https://github.com/fredvs/ideU/commit/ea3c10f2c7b333977c9d14d7e46a3c590bfebb2a) should have fixed it.

Compiled and tested  on a real Windows 10 machine.

The binaries of release for Windows 64/32 are updated in the assets:
https://github.com/fredvs/ideU/releases/

I hope it works for you now.

Many thanks to note it.

Fre;D
