### ISSUE TITLE
How to enlarge the UI fonts?

### ISSUE THREAD

**Issue by s6nonqxt** [fredvs/ideU#44]
It's too small on my monitor. I'm unable to read.

**Comment by fredvs** [comment]
You may change the UI font with Menu / Settings / Extra Settings and change the font height like you want.

![etra-settings-ideu](https://user-images.githubusercontent.com/3421249/204161691-1714d8a0-442a-401b-9b40-38efd2efa666.png)

You may also set it with Menu / Language.
On the right side, choose the size of the font.

![languages-ideu](https://user-images.githubusercontent.com/3421249/204161780-0dd50c26-244b-455f-af56-d0277b5c703e.png)
