### ISSUE TITLE
Add console application project support

### ISSUE THREAD

**Issue by s6nonqxt** [fredvs/ideU#46]
Please add at least it. Other project types have been TODO for a long time.

**Comment by fredvs** [comment]
You may choose the type of project at creation Menu / Project / New / From template:

![project-new-template-ideu](https://user-images.githubusercontent.com/3421249/204162051-10d8b550-f057-4c70-a71f-eeb094f68c44.png)

But maybe I did not catch what you want, if so, please explain.
