### ISSUE TITLE
How to dock everything into just one window?

### ISSUE THREAD

**Issue by s6nonqxt** [fredvs/ideU#47]
I hate this style of old Photoshop and the Gimp's interface. On Lazarus, we have anchordockingdsng. What about this?

**Comment by fredvs** [comment]
Take a look at Menu / Layout.
There are predefined layout, included all docked.

![layout-ideu](https://user-images.githubusercontent.com/3421249/204162548-e4c5b416-fb76-4f4d-b688-8f1fac64ceb5.png)

With MSEgui, there is on the right side of each window a grip-panel for anchordocking.
Click on it maintaining the button and move the window in a dock or float it.

Also there are icons on top of the grip-panel to float, stick, ...  the windows. (see the hint for each button)

![gripp-anchordock-ideu](https://user-images.githubusercontent.com/3421249/204162524-023e0fa5-4d79-459a-85dc-3ba7734b504b.png)
