### ISSUE TITLE
Refine the UI to be more logical

### ISSUE THREAD

**Issue by s6nonqxt** [fredvs/ideU#48]
I can't stand the UI. It's so illogical and counter-intuitive. What does Make 1, Make 2,... and many other Make N means? What is the different between Project and Edited? And so many illogical and counter-intuitive design. I have an impression that it's just patch work by someone on his spare time, the design only make senses to him as he and only he is used with it. With other people, it's only confusing!

**Comment by fredvs** [comment]
> What is the different between Project and Edited?

The Project panel control the project himself (in fpc the "program" or "library" unit).
The Edited panel control the active edited source ( like Geany does, so you may use different language/compiler in a project ).

> What does Make 1, Make 2,... and many other Make N means?

In project-option, you may have Make, Build, Make 0 to Make 9 different options to compile the project.
In the commander panel, you may choose what option you want for compilation of the project.

The same if you want to compile only the active edited source. 

> I have an impression that it's just patch work by someone on his spare time, the design only make senses to him as he > and only he is used with it. With other people, it's only confusing!

Yes, I agree and if you try MSEide it is even more confusing.
But, with some perseverance, you will see that the logical of Martin is very interesting.
