### ISSUE TITLE
Default ${target} values in Release 1.1.0 for FreeBSD

### ISSUE THREAD

**Issue by graemeg** [fredvs/ideU#5]
I just installed a new ideU of v1.1.0. Very impressive what I have seen so far. When the IDE started up for the first time, the Global Settings dialog appeared automatically. I verified the values, and noticed that the value of ${target} was "x86_64-linux", when I'm running 64-bit FreeBSD and the FreeBSD release of ideU.

This is a small issue, as those values only ever need to be set once, but I thought I would mention in anyway.

**Comment by fredvs** [comment]
Hello Graeme.

Thanks to try ideU ;-)

> x86_64-linux

Huh, I know this and have already talk about this with Martin.
I would prefer "x86_64-unix" or "x86_64-freebsd"

With first release of ideU this was changed (in MSEgui code).
But to maintain compatibility with MSEgui, I stop this.

PS: If you you convince Martin that FreeBSD is not Linux, maybe he could permanently fix it.

Fre;D

**Comment by graemeg** [comment]
Hi Fred. I think you confused what I was reporting. I know MSEgui has hard-coded "linux" directory inside the "lib/*" directory hierarchy. That is *not* what I was referring too. The ${target} macro is the value used for the default unit output directory. Normally that value will match the platform you are running on. You would only change that if you do cross-compiling. The ${target} macro also has nothing to do with MSEgui - that value is used even for Console or fpGUI applications too.

eg: In my Project Options -> Make Options, I'll define a entry as follows:
`-FUunits/${Target}/`

That defines the directory where compiled units will go. The *.ppu, *.o, *.a etc files.

**Comment by fredvs** [comment]
Ha, ok.

I will check this asap (do not have my laptop here).

Write you later.

Fre;D

**Comment by graemeg** [comment]
No rush! Like I said, those values don't really change much once they are set.

**Comment by fredvs** [comment]
Oooops, well seen Graeme.

Indeed there was a bug.
Fixed in last commit: 40c0d87..22cda0f

Thanks.

Fre;D
