### ISSUE TITLE
fpGUI project templates seem faulty

### ISSUE THREAD

**Issue by graemeg** [fredvs/ideU#6]
See attached screenshot. This is what I saw after I selected "Project -> new from template" and selected "fpgui/fpg_program.prj". It seem the template is not correctly referencing the template "units" directory layout.

![screenshot at 2016-10-26 09 41 55](https://cloud.githubusercontent.com/assets/72053/19719134/8614624c-9b60-11e6-874c-4ee588131403.png)

**Comment by fredvs** [comment]
Ooops, ok, I will check this.

Fre;D

**Comment by fredvs** [comment]
Hello Graeme.

I did some fixes in last commit: 40c0d87..22cda0f

Here video of what appends on my system:
[https://sites.google.com/site/designerext/ideu_new_fpgui.mp4]

PS: You need to create a  /units folder in directory of project.
Maybe it will be cool to create that /units directory automatic.

Fre;D

**Comment by graemeg** [comment]
Thanks Fred, I'll update and take another look.

As for automatically creating the "units/" directory hierarchy - yes that is already possible, and what I have done in my own MSEide templates directory. The required settings are shown in the "Project Options -> Templates -> New Project" screen. 

Take a look at the attached template .prj file - more specifically the **newprojectfiles** and **newprojectfilesdest** settings. I had to add a ".txt" extension, otherwise Github would not accept the attachment.

[fpgui.prj.txt](https://github.com/fredvs/ideU/files/554820/fpgui.prj.txt)

**Comment by fredvs** [comment]
OK, thanks Graeme, I will study all that and write you later.

**Comment by fredvs** [comment]
Hello Graeme.

OK, thanks for the tip, this makes it better:

makeoptions=7
...
 -FUunits/${TARGET}/
...

newprojectfiles=8
 ${TEMPLATEDIR}/fpc_fpgui/files/fpg_program.pas
 ${TEMPLATEDIR}/fpc_fpgui/files/frm_main.pas
 ${TEMPLATEDIR}/fpc_fpgui/files/dummy
 ${TEMPLATEDIR}/fpc_fpgui/files/dummy
 ${TEMPLATEDIR}/fpc_fpgui/files/dummy
 ${TEMPLATEDIR}/fpc_fpgui/files/dummy
 ${TEMPLATEDIR}/fpc_fpgui/files/dummy
 ${TEMPLATEDIR}/fpc_fpgui/files/dummy

newprojectfilesdest=8
 ${%PROJECTNAME%}.pas
 frm_main.pas
 ${%PROJECTDIR%}/units/i386-linux/dummy
 ${%PROJECTDIR%}/units/i386-freebsd/dummy
 ${%PROJECTDIR%}/units/i386-win32/dummy
 ${%PROJECTDIR%}/units/x86_64-linux/dummy
 ${%PROJECTDIR%}/units/x86_64-freebsd/dummy
 ${%PROJECTDIR%}/units/x86_64-win64/dummy

Added fpg_single.prj and fpg_units.prj in /templates.

Note that, with ideU, ${FPGUIDIR} is a build-in-defined macro.

Fred;D

**Comment by graemeg** [comment]
Awesome, thanks.
