### ISSUE TITLE
syntax highlighting seems to have a problem

### ISSUE THREAD

**Issue by graemeg** [fredvs/ideU#7]
The default ideu.sdef seems to have a problem with Object Pascal files. See attached screenshot. The compiler directives on lines 3, 6 and 8 is a bit confusing or inconsistent. Why are some in red and others in blue. First I thought is is matching nested blocks, but it's not, because the blue IFDEF on line 6 doesn't match the blue ENDIF on line 8.

![screenshot](https://cloud.githubusercontent.com/assets/72053/19719392/9c2b5c2e-9b61-11e6-96c5-79a651ecae20.png)

The default sdef from MSEide doesn't have this problem, so it seem specific to ideU customisations of the sdef file.

**Comment by fredvs** [comment]
Thanks to report it.

I will check this asap.

Fre;D

**Comment by fredvs** [comment]
Ok, fixed in last commit: 40c0d87..22cda0f

Thanks to note it.

Fre;D
